### ISSUE TITLE
Connection drops

### ISSUE THREAD

**Issue by vitalik** [jordaneremieff/django-fastapi-example#1]
Hi

have you tried your approach with mysql or postgres ?
The issue I encountered is that fastapi/async does not provide good place to ensure that db connection is still active 

https://github.com/tiangolo/fastapi/issues/716

**Comment by jordaneremieff** [comment]
I tried using Postgres instead of SQLite briefly and didn't run into any issues, though my testing has been limited. What is the approach you've taken?

**Comment by vitalik** [comment]
what I can reproduce - take default mysql, run your app with i bit of heavy load (like refresh page few times is enough)
then wait 30-60 minutes
try again - make few requests to resource that takes data from db - error

**Comment by jordaneremieff** [comment]
@vitalik is this only when using async FastAPI or with the example code here exactly? And how are you running the server? Also, could you post the error traceback?

It's difficult to find a solution without more information, but I'm willing to help if I know more about the problem you're running into. And the [Channels](https://github.com/django/channels/issues) tracker might be worth a search in case similar issues were encountered before.
